import React, { memo, useCallback, useEffect, useMemo, useState } from "react";
import {
  SortableContext,
  verticalListSortingStrategy,
  useSortable,
} from "@dnd-kit/sortable";
import { useDroppable } from "@dnd-kit/core";
import { CSS } from "@dnd-kit/utilities";
import type { SectionBlock, BlockType, BreakpointId } from "../types.js";
import { isContainerType } from "../types.js";
import { PREVIEW_COMPONENTS } from "./previews/index.js";
import { BlockOverlay } from "./BlockOverlay.js";
import { BlockErrorBoundary } from "./components/BlockErrorBoundary.js";
import {
  buildBlockCss,
  buildHoverCss,
  buildImgVisualCss,
  buildImgVisualHoverCss,
  getCustomCss,
} from "../components/styleUtils.js";

export const CANVAS_DROP_ID = "canvas-drop";

// ─── Drag data types (exported for BuilderPage) ───────────────────────────────

export type BlockDragData = {
  kind: "block";
  containerId: string | null;
  slotIndex: number | null;
  isContainer: boolean;
};

export type EmptyZoneData = {
  kind: "empty-zone";
  containerId: string;
  slotIndex: number | null;
};

// ─── Style helpers ────────────────────────────────────────────────────────────
//
// All visual block CSS is generated by `../components/styleUtils.ts` (the same
// module the frontend Astro components use) and injected into the document as
// a single global <style> element. Canvas does NOT compute inline styles for
// background / border / radius / shadow / typography / position. Container
// children-wrapper layout (display/flex/grid) is the one exception — it stays
// inline because it's specific to admin canvas mounting and isn't represented
// in styleUtils' selector output.
//
// To preview a non-desktop breakpoint, `buildEffectiveBlockCss` synthetically
// merges `styleBreakpoints[bp]` into `style` (and the hover counterpart) so the
// emitted rule matches what the frontend's @media query would render — but the
// canvas itself remains at full window width, so we can't rely on the actual
// @media to fire.

function buildEffectiveBlockCss(
  block: SectionBlock,
  activeBreakpoint: BreakpointId,
): string {
  const config = block.config as Record<string, unknown>;
  const isImage = block.type === "image";
  const opts = isImage ? { imgScoped: true } : undefined;

  const styleBp = activeBreakpoint !== "desktop"
    ? (config.styleBreakpoints as Record<string, Record<string, unknown>> | undefined)?.[activeBreakpoint]
    : undefined;
  const styleHoverBp = activeBreakpoint !== "desktop"
    ? (config.styleHoverBreakpoints as Record<string, Record<string, unknown>> | undefined)?.[activeBreakpoint]
    : undefined;

  const cfg = (styleBp || styleHoverBp)
    ? {
        ...config,
        style: { ...((config.style as Record<string, unknown>) ?? {}), ...(styleBp ?? {}) },
        styleHover: { ...((config.styleHover as Record<string, unknown>) ?? {}), ...(styleHoverBp ?? {}) },
      }
    : config;

  let out = buildBlockCss(cfg, block.id, opts);
  out += buildHoverCss(cfg, block.id, opts);
  if (isImage) {
    out += buildImgVisualCss(cfg, block.id);
    out += buildImgVisualHoverCss(cfg, block.id);
  }
  out += getCustomCss(cfg, block.id);
  return out;
}

// ─── Canvas Props ─────────────────────────────────────────────────────────────

interface CanvasProps {
  sections: SectionBlock[];
  selectedId: string | null;
  onSelect: (id: string | null) => void;
  onRemove: (id: string) => void;
  onAddToContainer: (containerId: string, slotIndex: number | null, type: BlockType) => void;
  dropIndicatorId: string | null;
  onAddAfter: (afterId: string, type: BlockType) => void;
  previewWidth?: number | null;
  resizeBounds?: { min: number; max: number } | null;
  onWidthChange?: (w: number | null) => void;
  onBlockContextMenu?: (e: React.MouseEvent, id: string) => void;
  activeBreakpoint: BreakpointId;
}

// ─── Canvas ───────────────────────────────────────────────────────────────────

export function Canvas({
  sections,
  selectedId,
  onSelect,
  onRemove,
  onAddToContainer,
  dropIndicatorId,
  onAddAfter,
  previewWidth,
  resizeBounds,
  onWidthChange,
  onBlockContextMenu,
  activeBreakpoint,
}: CanvasProps) {
  const { setNodeRef: setCanvasRef } = useDroppable({ id: CANVAS_DROP_ID });

  // Local drag-resize width — resets whenever the active breakpoint changes (previewWidth changes)
  const [localWidth, setLocalWidth] = useState<number | null>(null);
  const [prevPreviewWidth, setPrevPreviewWidth] = useState(previewWidth);
  if (prevPreviewWidth !== previewWidth) {
    setPrevPreviewWidth(previewWidth);
    setLocalWidth(null);
  }

  const effectiveWidth = localWidth ?? previewWidth;

  useEffect(() => {
    onWidthChange?.(localWidth);
  }, [localWidth, onWidthChange]);

  // Recompute the full canvas stylesheet only when sections or active
  // breakpoint actually change — useMemo gives identity-stable output, so
  // the effect below skips DOM writes when neither dep moved (audit M6).
  // Per-block ref caching was prototyped but `react-hooks/refs` rejects
  // ref access in render; left as a follow-up if profiling shows the rebuild
  // is hot.
  const allBlockCss = useMemo(() => {
    function walk(list: SectionBlock[]): string {
      let out = "";
      for (const block of list) {
        out += buildEffectiveBlockCss(block, activeBreakpoint);
        if (block.children) out += walk(block.children);
        if (block.slots) block.slots.forEach((slot) => { out += walk(slot); });
      }
      return out;
    }
    return walk(sections);
  }, [sections, activeBreakpoint]);

  // Single global <style> with per-block CSS for the entire tree. Includes
  // base style + hover + per-breakpoint overrides + custom CSS, all routed
  // through the same styleUtils helpers the frontend uses, so canvas preview
  // and rendered output stay in sync.
  useEffect(() => {
    let el = document.getElementById("epx-canvas-block-css") as HTMLStyleElement | null;
    if (!el) {
      el = document.createElement("style");
      el.id = "epx-canvas-block-css";
      document.head.appendChild(el);
    }
    el.textContent = allBlockCss;
    return () => { el?.remove(); };
  }, [allBlockCss]);

  const handleResizeDragStart = useCallback((side: "left" | "right") => (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (!resizeBounds) return;
    const startX = e.clientX;
    const startWidth = effectiveWidth ?? resizeBounds.max;
    document.body.style.cursor = "ew-resize";
    document.body.style.userSelect = "none";
    document.body.classList.add("epx-resizing");
    let pending: number | null = null;
    let nextWidth = startWidth;
    const apply = () => {
      pending = null;
      setLocalWidth(nextWidth);
    };
    const onMove = (ev: MouseEvent) => {
      const delta = ev.clientX - startX;
      const raw = side === "right" ? startWidth + delta : startWidth - delta;
      nextWidth = Math.round(Math.max(resizeBounds.min, Math.min(resizeBounds.max, raw)));
      if (pending === null) pending = requestAnimationFrame(apply);
    };
    const onUp = () => {
      document.body.style.cursor = "";
      document.body.style.userSelect = "";
      document.body.classList.remove("epx-resizing");
      if (pending !== null) cancelAnimationFrame(pending);
      window.removeEventListener("mousemove", onMove);
      window.removeEventListener("mouseup", onUp);
    };
    window.addEventListener("mousemove", onMove);
    window.addEventListener("mouseup", onUp);
  }, [resizeBounds, effectiveWidth]);

  const showHandles = !!resizeBounds && !!effectiveWidth;
  const frameStyle = effectiveWidth
    ? showHandles
      ? { overflowX: "hidden" as const, width: "100%", maxWidth: effectiveWidth, flexShrink: 0 as const }
      : { maxWidth: effectiveWidth, width: "100%", margin: "0 auto" }
    : undefined;

  const isEmpty = sections.length === 0;
  const canvasClass = [
    "epx-canvas",
    isEmpty ? "epx-canvas--empty" : null,
    effectiveWidth ? "epx-canvas--preview" : null,
    showHandles ? "epx-canvas--resizable" : null,
  ].filter(Boolean).join(" ");

  const frameContent = isEmpty ? (
    <div className="epx-canvas__empty-state">
      <h3>Start building your page</h3>
      <p>Click or drag a block from the left panel</p>
    </div>
  ) : (
    <SortableContext items={sections.map((s) => s.id)} strategy={verticalListSortingStrategy}>
      <div className="epx-canvas__list">
        {sections.map((section) => {
          if (isContainerType(section.type)) {
            return (
              <ContainerBlock
                key={section.id}
                section={section}
                selectedId={selectedId}
                onSelect={onSelect}
                onRemove={onRemove}
                onAddToContainer={onAddToContainer}
                dropIndicatorId={dropIndicatorId}
                onAddAfter={onAddAfter}
                containerId={null}
                onBlockContextMenu={onBlockContextMenu}
                activeBreakpoint={activeBreakpoint}
              />
            );
          }
          return (
            <SortableBlock
              key={section.id}
              section={section}
              containerId={null}
              slotIndex={null}
              isSelected={section.id === selectedId}
              onSelect={() => onSelect(section.id)}
              onRemove={() => onRemove(section.id)}
              isDropTarget={section.id === dropIndicatorId}
              onAddAfter={(type) => onAddAfter(section.id, type)}
              onBlockContextMenu={onBlockContextMenu}
              activeBreakpoint={activeBreakpoint}
            />
          );
        })}
      </div>
    </SortableContext>
  );

  return (
    <main ref={setCanvasRef} className={canvasClass} onClick={() => onSelect(null)}>
      {showHandles && (
        <div className="epx-canvas__side-handle epx-canvas__side-handle--left" onMouseDown={handleResizeDragStart("left")}>
          <div className="epx-canvas__side-grip" />
        </div>
      )}
      <div className="epx-canvas__preview-frame" style={frameStyle}>
        {frameContent}
      </div>
      {showHandles && (
        <div className="epx-canvas__side-handle epx-canvas__side-handle--right" onMouseDown={handleResizeDragStart("right")}>
          <div className="epx-canvas__side-grip" />
        </div>
      )}
    </main>
  );
}

// ─── SortableBlock ─────────────────────────────────────────────────────────────

interface SortableBlockProps {
  section: SectionBlock;
  containerId: string | null;
  slotIndex: number | null;
  isSelected: boolean;
  onSelect: () => void;
  onRemove: () => void;
  isDropTarget: boolean;
  onAddAfter: (type: BlockType) => void;
  onBlockContextMenu?: (e: React.MouseEvent, id: string) => void;
  activeBreakpoint: BreakpointId;
}

function SortableBlock({
  section,
  containerId,
  slotIndex,
  isSelected,
  onSelect,
  onRemove,
  isDropTarget,
  onAddAfter,
  onBlockContextMenu,
  activeBreakpoint,
}: SortableBlockProps) {
  const [hovered, setHovered] = useState(false);
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: section.id,
    data: {
      kind: "block",
      containerId,
      slotIndex,
      isContainer: false,
    } satisfies BlockDragData,
  });

  // All visual / layout / position styling is emitted into the global
  // <style> via collectAllBlockCss (see Canvas function above) and targets
  // [data-epx-block="<id>"]. Wrapper here only carries dnd-kit transform.
  const wrapperStyle: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.4 : 1,
  };

  const Preview = PREVIEW_COMPONENTS[section.type];
  const isInner = containerId !== null;

  return (
    <div
      ref={setNodeRef}
      style={wrapperStyle}
      className={`epx-block-preview${isSelected ? " is-selected" : ""}`}
      onClick={(e) => { e.stopPropagation(); onSelect(); }}
      onContextMenu={(e) => onBlockContextMenu?.(e, section.id)}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {isInner ? (
        <InnerBlockOverlay
          visible={hovered || isSelected}
          dragListeners={listeners}
          dragAttributes={attributes}
          onSelect={onSelect}
        />
      ) : (
        <BlockOverlay
          visible={hovered || isSelected}
          onAdd={onAddAfter}
          dragListeners={listeners}
          dragAttributes={attributes}
          onDelete={onRemove}
          onSelect={onSelect}
        />
      )}

      <div
        data-epx-block={section.id}
        data-theme={(section.config.theme as string) === "dark" ? "dark" : undefined}
        className={`epx-theme--${(section.config.theme as string) || "light"}`}
      >
        <BlockErrorBoundary blockId={section.id}>
          {Preview ? (
            <Preview config={section.config} children={section.children} slots={section.slots} activeBreakpoint={activeBreakpoint} />
          ) : (
            <div style={{ padding: "12px 14px", color: "#888", fontSize: 12 }}>
              Unknown block: {section.type}
            </div>
          )}
        </BlockErrorBoundary>
      </div>

      {isDropTarget && <div className="epx-drop-indicator" />}
    </div>
  );
}

// ─── InnerBlockOverlay ────────────────────────────────────────────────────────

function InnerBlockOverlay({
  visible,
  dragListeners,
  dragAttributes,
  onSelect,
}: {
  visible: boolean;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  dragListeners: Record<string, any> | undefined;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  dragAttributes: Record<string, any> | undefined;
  onSelect: () => void;
}) {
  return (
    <div
      className={`epx-inner-block-overlay${visible ? " is-visible" : ""}`}
      onClick={(e) => { e.stopPropagation(); onSelect(); }}
    >
      <div
        className="epx-inner-block-overlay__handle"
        {...dragListeners}
        {...dragAttributes}
        title="Drag to reorder"
      >
        ⠿
      </div>
    </div>
  );
}

// ─── ContainerBlock ───────────────────────────────────────────────────────────

interface ContainerBlockProps {
  section: SectionBlock;
  selectedId: string | null;
  onSelect: (id: string | null) => void;
  onRemove: (id: string) => void;
  onAddToContainer: (containerId: string, slotIndex: number | null, type: BlockType) => void;
  dropIndicatorId: string | null;
  onAddAfter: (afterId: string, type: BlockType) => void;
  containerId: string | null;
  onBlockContextMenu?: (e: React.MouseEvent, id: string) => void;
  activeBreakpoint: BreakpointId;
}

const ContainerBlock = memo(function ContainerBlock({
  section,
  selectedId,
  onSelect,
  onRemove,
  onAddToContainer,
  dropIndicatorId,
  onAddAfter,
  containerId,
  onBlockContextMenu,
  activeBreakpoint,
}: ContainerBlockProps) {
  const [hovered, setHovered] = useState(false);
  const isSelected = section.id === selectedId;
  const children = section.children ?? [];

  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: section.id,
    data: {
      kind: "block",
      containerId,
      slotIndex: null,
      isContainer: true,
    } satisfies BlockDragData,
  });

  // Visual styling (bg/border/radius/shadow/etc.) is injected globally via
  // collectAllBlockCss and targets [data-epx-block]. Only dnd transform here.
  const style: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.4 : 1,
  };

  return (
    <div
      ref={setNodeRef}
      data-epx-block={section.id}
      data-theme={(section.config.theme as string) === "dark" ? "dark" : undefined}
      style={style}
      className={`epx-container-block epx-theme--${(section.config.theme as string) || "light"}${isSelected ? " is-selected" : ""}`}
      onClick={(e) => { e.stopPropagation(); onSelect(section.id); }}
      onContextMenu={(e) => onBlockContextMenu?.(e, section.id)}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
    >
      {containerId !== null ? (
        <InnerBlockOverlay
          visible={hovered || isSelected}
          dragListeners={listeners}
          dragAttributes={attributes}
          onSelect={() => onSelect(section.id)}
        />
      ) : (
        <BlockOverlay
          visible={hovered || isSelected}
          onAdd={(type) => onAddAfter(section.id, type)}
          dragListeners={listeners}
          dragAttributes={attributes}
          onDelete={() => onRemove(section.id)}
          onSelect={() => onSelect(section.id)}
        />
      )}

      <SortableContext items={children.map((c) => c.id)} strategy={verticalListSortingStrategy}>
        <div
          className="epx-container-block__children"
          style={(() => {
            const layout = (section.config.layout as string) ?? "flex";
            const configStyle = (section.config.style as Record<string, unknown> | undefined) ?? {};
            const bpOverride = (activeBreakpoint !== "desktop"
              ? (section.config.styleBreakpoints as Record<string, Record<string, unknown>> | undefined)?.[activeBreakpoint]
              : undefined) ?? {};
            const isGrid = layout === "grid";
            const resolveTrack = (raw: unknown): string | undefined => {
              if (typeof raw !== "string" || !raw) return undefined;
              if (raw.startsWith("@@")) return raw.slice(2) || undefined;
              return raw;
            };
            const bp = bpOverride as Record<string, unknown>;
            return {
              display:               isGrid ? "grid" : "flex",
              columnGap:             (bp.columnGap ?? configStyle.columnGap) as string | undefined,
              rowGap:                (bp.rowGap    ?? configStyle.rowGap)    as string | undefined,
              flexWrap:              !isGrid ? (((bp.flexWrap       ?? section.config.flexWrap)       as string) ?? "nowrap")     as React.CSSProperties["flexWrap"]       : undefined,
              flexDirection:         !isGrid ? (((bp.flexDirection  ?? section.config.flexDirection)  as string) ?? "row")        as React.CSSProperties["flexDirection"]  : undefined,
              justifyContent:        !isGrid ? (((bp.justifyContent ?? section.config.justifyContent) as string) ?? "flex-start") as React.CSSProperties["justifyContent"] : undefined,
              alignItems:            !isGrid ? (((bp.flexAlignItems ?? section.config.flexAlignItems) as string) ?? "stretch")    as React.CSSProperties["alignItems"]
                                             : ((section.config.alignItems    as string) ?? "stretch"),
              gridAutoFlow:          isGrid  ? ((section.config.gridFlow       as string) ?? "row")        : undefined,
              justifyItems:          isGrid  ? ((section.config.justifyItems   as string) ?? "stretch")    : undefined,
              gridTemplateColumns:   isGrid  ? resolveTrack(section.config.gridColumns)                    : undefined,
              gridTemplateRows:      isGrid  ? resolveTrack(section.config.gridRows)                       : undefined,
            };
          })()}
        >
          {children.length > 0 ? (
            children.map((child) =>
              isContainerType(child.type) ? (
                <ContainerBlock
                  key={child.id}
                  section={child}
                  selectedId={selectedId}
                  onSelect={onSelect}
                  onRemove={onRemove}
                  onAddToContainer={onAddToContainer}
                  dropIndicatorId={dropIndicatorId}
                  onAddAfter={onAddAfter}
                  containerId={section.id}
                  onBlockContextMenu={onBlockContextMenu}
                  activeBreakpoint={activeBreakpoint}
                />
              ) : (
                <SortableBlock
                  key={child.id}
                  section={child}
                  containerId={section.id}
                  slotIndex={null}
                  isSelected={child.id === selectedId}
                  onSelect={() => onSelect(child.id)}
                  onRemove={() => onRemove(child.id)}
                  isDropTarget={child.id === dropIndicatorId}
                  onAddAfter={(type) => onAddAfter(child.id, type)}
                  onBlockContextMenu={onBlockContextMenu}
                  activeBreakpoint={activeBreakpoint}
                />
              )
            )
          ) : (
            <EmptyDropZone
              containerId={section.id}
              slotIndex={null}
            />
          )}
        </div>
      </SortableContext>

      {section.id === dropIndicatorId && <div className="epx-drop-indicator" />}
    </div>
  );
});

// ─── EmptyDropZone ────────────────────────────────────────────────────────────

function EmptyDropZone({
  containerId,
  slotIndex,
}: {
  containerId: string;
  slotIndex: number | null;
}) {
  const id = `empty:${containerId}:${slotIndex ?? "c"}`;
  const { setNodeRef, isOver } = useDroppable({
    id,
    data: { kind: "empty-zone", containerId, slotIndex } satisfies EmptyZoneData,
  });

  return (
    <div
      ref={setNodeRef}
      className={`epx-container__empty-zone${isOver ? " is-over" : ""}`}
      onClick={(e) => e.stopPropagation()}
    >
      <span style={{ fontSize: 11, color: "var(--epx-text-muted)", opacity: 0.6 }}>Drop blocks here</span>
    </div>
  );
}
